name: Lint

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  check-eol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check line endings
        run: |
          if grep -rIl $'\r' . --exclude-dir=.git --exclude-dir=node_modules; then
            echo "CRLF line endings found"
            exit 1
          fi

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install eslint
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_fix: true
          eslint: true

  lint-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_fix: true
          clang_format: true